name: biribi_financas
description: Fabrica.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  flutter_secure_storage: ^3.3.1+1
  rxdart: ^0.22.0
  sqflite: ^1.2.0
  flutter_masked_text: ^0.8.0
  google_maps_flutter: ^0.5.22
  flutter_google_places: ^0.2.3
  geolocator: ^5.2.1
  flutter_speed_dial: ^1.2.5
  google_map_location_picker: ^3.2.0
  google_maps_webservice: ^0.0.16
  provider: ^4.0.2
  flutter_datetime_picker: ^1.3.4
  font_awesome_flutter: ^8.5.0
  maps_launcher: ^1.2.0
  sticky_infinite_list: ^1.2.3
  intl: ^0.16.0
  cupertino_icons: ^0.1.2
  table_calendar: ^2.2.2
  loading: ^1.0.2
  flutter_week_view: ^0.2.1+2
  calendar_views: ^0.5.2
  url_launcher: ^5.4.1
  meta: ^1.1.6
  date_format: ^1.0.8
  fl_chart: ^0.8.0
  carousel_slider: ^1.4.1
  photo_view: ^0.9.2
  flutter_downloader: ^1.4.1
  shared_preferences: ^0.5.6+1
  path_provider: ^1.6.0
  open_file: ^3.0.1
  date_util: ^0.1.4
  majascan: ^0.3.5
  shimmer: ^1.0.1
  flutter_svg: ^0.17.1
  mime: ^0.9.6+3
  socket_io_client: ^0.9.7+2
  laravel_echo: ^0.2.2
  date_utils: ^0.1.0+3
  video_player: ^0.10.8+1
  chewie: ^0.9.8+1
  validators: ^2.0.0
  flushbar: ^1.9.1
  dio: ^3.0.9
  overlay_support: ^1.0.3
  neat_periodic_task: ^1.0.1
  #ounded_floating_app_bar: ^0.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png


flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
  #   - assets/images/logo.svg
  #   - assets/images/produto.png
  #   - assets/images/malha.jpg
  #   - assets/images/dalila.png
  #  - images/a_dot_ham.jpeg


modules:
  androidX: true
